services:
  - type: web
    name: detector-anomalias-nosql
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: MONGO_URI
        sync: false

      - key: MONGO_DB
        value: anomaly_detector

      - key: SECRET_KEY
        generateValue: true

      - key: JWT_ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"